name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, reopened, edited, closed, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          not-before: 2020-01-15T02:54:32Z
          enable-versioned-regex: 1
          versioned-regex: 'issue_labeler_regex_version=(\d+)'
          body-missing-regex-label: "broken-template"
